# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61473ef2366a7cd09ef6ad973160fc2890bcfc350d961829014538bd99f4fe567854c2f1835a110fbe6d1807fcf39973daeb1993d9446ee2673cd6fd776b1bc2

test:
  secret_key_base: 87b5e9b39715777e6aa5dc5116b6396c2e14627e83876e3f05628262c0b796b2dc1bcadb3e1dc90975b9ae3fd661b5e4fe344d9ab3f39e1fe1359db06b6388ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
